// <auto-generated />
using System;
using BackendTemplate.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendTemplate.Migrations
{
    [DbContext(typeof(PlutoContext))]
    [Migration("20211102225246_SeederProjects")]
    partial class SeederProjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BackendTemplate.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BackendTemplate.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Btw_Number")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BackendTemplate.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Estimated_Finish_Time")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Neque aut sunt quam architecto est magni aperiam suscipit consectetur. Nobis placeat aut velit recusandae aut vel doloribus. Deserunt dolorum velit illo sed. Fugit sit eius qui. Repudiandae fugiat enim error vel numquam dolore id. Velit voluptas ratione qui expedita tempore quaerat dicta omnis.",
                            Price = 2083907603,
                            Title = "Illo provident aut tempora."
                        },
                        new
                        {
                            ID = 2,
                            Description = "Amet error repellendus omnis delectus. Qui excepturi pariatur incidunt placeat. Quasi qui et ad illum aut eos tenetur aut autem.",
                            Price = 960685830,
                            Title = "Quia assumenda voluptatem sed animi."
                        },
                        new
                        {
                            ID = 3,
                            Description = "Dolorem quis et aliquid qui velit facere harum eius. Ut accusamus voluptatem occaecati minus. Assumenda sed qui quia recusandae dolores in qui beatae. Ad ut nam voluptatem temporibus. Animi odio repudiandae in soluta aspernatur aperiam corrupti. Provident minus et ut.",
                            Price = 1108338971,
                            Title = "Hic magni provident quasi nihil blanditiis."
                        },
                        new
                        {
                            ID = 4,
                            Description = "Molestiae consequuntur excepturi est id. Et repellendus voluptatem et et aut voluptatem ab velit. Sed et aut aut tempora et placeat totam laboriosam saepe. Aut fugiat eius voluptas. Molestiae facilis voluptatem accusamus. Est illo temporibus et magnam sunt dolores.",
                            Price = 1580233136,
                            Title = "Non quae et porro qui est consequuntur cumque."
                        },
                        new
                        {
                            ID = 5,
                            Description = "Voluptatem nisi aperiam dolor deleniti non quo. Veritatis distinctio asperiores aut. Voluptate eveniet quidem adipisci autem nemo quibusdam ad magni. Maxime sint mollitia nisi porro enim. Ad saepe doloribus possimus libero quas eum ducimus qui distinctio.",
                            Price = 1294482929,
                            Title = "Debitis error expedita fugiat deserunt debitis nihil."
                        },
                        new
                        {
                            ID = 6,
                            Description = "Atque sit ex magnam. Doloremque dignissimos laudantium ea sed aut. Et et fugiat impedit harum. Sapiente ea voluptatem accusamus et et omnis. Voluptatem fuga aut laboriosam sit iste ut suscipit occaecati recusandae. Temporibus quae quam quas deserunt assumenda.",
                            Price = 1392247070,
                            Title = "Eligendi ipsum aspernatur qui sunt et."
                        },
                        new
                        {
                            ID = 7,
                            Description = "Similique nostrum qui sunt cum occaecati aut aliquid est. Magni voluptas est doloremque ipsam dolore. Sunt consequatur est dolores. Natus maiores voluptas porro suscipit et quia.",
                            Price = 520967837,
                            Title = "Vitae autem ex ut ut placeat magni vel sint porro."
                        },
                        new
                        {
                            ID = 8,
                            Description = "Aliquam sed quaerat totam eligendi. Iure odit ipsa autem. Officia saepe nesciunt tempora qui eveniet. Omnis aut aut assumenda aliquid. Quod nihil iusto quia et aut. Et quis assumenda et possimus veritatis.",
                            Price = 2101402866,
                            Title = "Commodi enim vel tempora voluptatem ipsa et sed consectetur est."
                        },
                        new
                        {
                            ID = 9,
                            Description = "Sunt magni aut non cupiditate rerum alias omnis. Temporibus consequatur esse omnis. Deleniti sed qui non.",
                            Price = 2002717099,
                            Title = "Et eveniet qui ducimus eius perspiciatis qui."
                        },
                        new
                        {
                            ID = 10,
                            Description = "Repudiandae aspernatur et laudantium ea. Quo incidunt ea aliquam et vero iure. Tempora sunt deleniti rerum ab ut et velit. Aut ex hic quo repudiandae accusantium amet veritatis. Repudiandae similique distinctio odit veniam illo magnam.",
                            Price = 380767352,
                            Title = "Laboriosam earum rerum ea et quia tempore."
                        },
                        new
                        {
                            ID = 11,
                            Description = "Asperiores sed id consequatur. Sit eveniet ut cum aut illo similique eligendi. Facilis laboriosam quia tenetur explicabo illum odio vero neque.",
                            Price = 259513261,
                            Title = "Et iusto culpa voluptate consequatur a porro sit enim voluptatem."
                        },
                        new
                        {
                            ID = 12,
                            Description = "Atque est non dolores voluptatibus ut. Vero qui harum id et exercitationem illum inventore dolores iusto. Deleniti nemo dolor et illum.",
                            Price = 104424867,
                            Title = "Nihil a id at."
                        },
                        new
                        {
                            ID = 13,
                            Description = "Repellat mollitia hic earum quam libero est. Nulla ut recusandae est non omnis dignissimos non reiciendis. Natus nobis dolores et similique. Omnis aut dolorum exercitationem. Rerum enim quaerat ipsum quisquam temporibus. Minima sint expedita ipsa suscipit nam similique aut nesciunt quos.",
                            Price = 1606284982,
                            Title = "Unde nisi velit dolor qui voluptatem ut est."
                        },
                        new
                        {
                            ID = 14,
                            Description = "Maxime iure aliquam quasi impedit nihil molestiae et. Explicabo rem eaque fugiat omnis. Quia omnis eum commodi vel est at non. Architecto ut asperiores nihil eum quam voluptates id repellat. Eum esse placeat nam dolores minus quo.",
                            Price = 830062820,
                            Title = "Reprehenderit et consequuntur cumque laudantium magni omnis natus."
                        },
                        new
                        {
                            ID = 15,
                            Description = "Est doloremque dolorem molestiae magni qui eaque voluptatibus ullam ex. Quod consequatur omnis voluptas sint consectetur non ut et. Ea est recusandae voluptatum quaerat. Dolores nihil dolor vitae veniam culpa modi distinctio assumenda consequatur. Autem maiores aliquam et beatae. Delectus qui corporis quos beatae assumenda.",
                            Price = 1440713107,
                            Title = "Fugit consequatur rerum veniam mollitia."
                        },
                        new
                        {
                            ID = 16,
                            Description = "Alias accusamus maxime et a. Vero aut quia excepturi dignissimos optio maiores voluptatibus et. Doloremque quasi earum earum sint sint minima.",
                            Price = 1465040543,
                            Title = "Deleniti eveniet sit et soluta natus ipsum ut quasi harum."
                        },
                        new
                        {
                            ID = 17,
                            Description = "Et modi corporis placeat. Illo cum est exercitationem. Non omnis in dolorum. Omnis numquam doloremque sunt aliquam sit et illum quaerat.",
                            Price = 1535919732,
                            Title = "Sequi pariatur laboriosam amet sed laboriosam cumque velit."
                        },
                        new
                        {
                            ID = 18,
                            Description = "Aut quam rem amet fugit. Nihil culpa eum sunt quia quia doloremque officia pariatur eveniet. Eius mollitia quod enim explicabo tenetur animi sunt doloremque omnis. Consequuntur nemo vitae vel. Dignissimos iusto distinctio harum soluta sed distinctio sequi quis.",
                            Price = 2137098458,
                            Title = "Voluptatem sunt ea aut vitae enim omnis et quam et."
                        },
                        new
                        {
                            ID = 19,
                            Description = "Qui eveniet non cumque autem. Ut et ut laudantium aut praesentium accusamus sed similique. Libero eum dolores distinctio magnam similique sit ipsa occaecati. Impedit architecto est ab maiores voluptatibus qui qui sapiente sit. Alias consequatur qui placeat suscipit quos. Est enim quibusdam aut dolorum incidunt aperiam beatae alias.",
                            Price = 729204488,
                            Title = "Voluptatem quae eaque deleniti aut aut at sequi aperiam."
                        },
                        new
                        {
                            ID = 20,
                            Description = "Non debitis voluptatum dolorem. Sed totam sequi voluptatem. Incidunt ducimus consequatur error nisi porro aut. Quia enim maiores amet inventore. In sequi non optio libero et maiores.",
                            Price = 382847657,
                            Title = "Corrupti quaerat similique amet voluptate aut esse vel sequi enim."
                        },
                        new
                        {
                            ID = 21,
                            Description = "Inventore porro at ut et sed. Rerum quis optio et est quo quas sequi laborum iste. Qui nihil corporis omnis vel iste voluptatibus dignissimos. Ea autem similique pariatur in. Reiciendis ab voluptatum ad sunt corrupti consequuntur distinctio aliquid. Ut et dolor facere magni.",
                            Price = 1185451298,
                            Title = "Possimus quia vel quaerat ipsum incidunt ex nam deleniti."
                        },
                        new
                        {
                            ID = 22,
                            Description = "Facere aut eius dolor aut voluptate voluptatibus in id repellat. Qui aut possimus labore. Aspernatur consequuntur repellendus voluptatem laboriosam ad. Qui impedit ut maiores aut praesentium aperiam commodi ea.",
                            Price = 2109881646,
                            Title = "Vero commodi eos illo voluptas mollitia aut dolorum quia."
                        },
                        new
                        {
                            ID = 23,
                            Description = "Et voluptatem impedit dolores corporis aperiam enim. Ratione dolorum officia non sunt facere eligendi sunt. Provident ex ratione et similique et.",
                            Price = 1180847266,
                            Title = "Natus nesciunt sit ut qui modi quibusdam dolore."
                        },
                        new
                        {
                            ID = 24,
                            Description = "Fuga dolore eum est quia. Et molestiae et est eius quia dignissimos corrupti. Temporibus aut molestiae dolore perferendis. Quidem beatae natus saepe odio doloribus enim itaque corrupti ut. Ullam et voluptas rem sequi sint ullam aut ut.",
                            Price = 469908886,
                            Title = "Qui et rerum repellat voluptatibus veritatis autem."
                        },
                        new
                        {
                            ID = 25,
                            Description = "Minus tempore eum enim dolore dolores. Tempora modi labore quis debitis voluptatibus omnis ut rerum voluptates. Cumque error et quia maiores. Soluta ipsa dolores odio similique similique possimus. Voluptates consequatur minus earum nobis porro ducimus soluta fugiat enim.",
                            Price = 391084296,
                            Title = "Porro voluptatem sit laboriosam minima corporis eum sit quo eos."
                        },
                        new
                        {
                            ID = 26,
                            Description = "Ab quis nostrum sit aut consectetur incidunt adipisci aperiam. Debitis est illo maiores magni quam tempore. Est perferendis assumenda sit pariatur distinctio sed. Culpa aspernatur voluptas unde unde delectus.",
                            Price = 589768412,
                            Title = "Sit repellendus iure quod cum ducimus blanditiis."
                        },
                        new
                        {
                            ID = 27,
                            Description = "Est rerum enim placeat rerum. Impedit ut quia est dicta est consequatur porro quam. Est aut quam quos eum illum porro eligendi.",
                            Price = 1937487694,
                            Title = "Veritatis autem commodi dolor et voluptatem molestias ullam."
                        },
                        new
                        {
                            ID = 28,
                            Description = "Corporis ut dolore fugiat sunt molestias. Omnis maiores dolores est. Tenetur qui pariatur totam quia ut eum.",
                            Price = 323224126,
                            Title = "Voluptatibus molestias perspiciatis in unde et quos."
                        },
                        new
                        {
                            ID = 29,
                            Description = "Ad vitae asperiores maiores magnam quia. Voluptate commodi quae repellendus voluptates dignissimos delectus dolorem. Non ut aut delectus enim dolores ea.",
                            Price = 747295443,
                            Title = "Voluptatem qui omnis dolore non ipsa recusandae voluptatem."
                        });
                });

            modelBuilder.Entity("BackendTemplate.Models.Subproject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Finish_Date")
                        .HasColumnType("text");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Start_Date")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Subprojects");
                });

            modelBuilder.Entity("ClientEmployee", b =>
                {
                    b.Property<int>("ClientsID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesID")
                        .HasColumnType("int");

                    b.HasKey("ClientsID", "EmployeesID");

                    b.HasIndex("EmployeesID");

                    b.ToTable("ClientEmployee");
                });

            modelBuilder.Entity("EmployeeSubproject", b =>
                {
                    b.Property<int>("EmployeesID")
                        .HasColumnType("int");

                    b.Property<int>("SubprojectsID")
                        .HasColumnType("int");

                    b.HasKey("EmployeesID", "SubprojectsID");

                    b.HasIndex("SubprojectsID");

                    b.ToTable("EmployeeSubproject");
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.HasOne("BackendTemplate.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientID");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BackendTemplate.Models.Subproject", b =>
                {
                    b.HasOne("BackendTemplate.Models.Category", "Category")
                        .WithMany("Subprojects")
                        .HasForeignKey("CategoryID");

                    b.HasOne("BackendTemplate.Models.Project", "Project")
                        .WithMany("Subprojects")
                        .HasForeignKey("ProjectID");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ClientEmployee", b =>
                {
                    b.HasOne("BackendTemplate.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTemplate.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeSubproject", b =>
                {
                    b.HasOne("BackendTemplate.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTemplate.Models.Subproject", null)
                        .WithMany()
                        .HasForeignKey("SubprojectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTemplate.Models.Category", b =>
                {
                    b.Navigation("Subprojects");
                });

            modelBuilder.Entity("BackendTemplate.Models.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.Navigation("Subprojects");
                });
#pragma warning restore 612, 618
        }
    }
}
