// <auto-generated />
using System;
using BackendTemplate.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendTemplate.Migrations
{
    [DbContext(typeof(PlutoContext))]
    partial class PlutoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BackendTemplate.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Dolor et blanditiis illum aspernatur earum ad quisquam. Dignissimos accusamus animi illum. Debitis quasi et suscipit repellat voluptas beatae vel rerum. Libero enim pariatur et expedita incidunt. Earum dolorem qui recusandae. Quisquam sequi voluptate distinctio.",
                            Name = "Earum aut nam eum perferendis qui est."
                        },
                        new
                        {
                            ID = 2,
                            Description = "Nemo commodi iste sint quae repudiandae culpa maxime necessitatibus. Minus deserunt in est doloribus iste a aspernatur exercitationem. Vel nesciunt impedit veritatis libero omnis dignissimos quia et minus.",
                            Name = "Consectetur alias dolorem impedit eveniet cupiditate rerum quas iure vitae."
                        },
                        new
                        {
                            ID = 3,
                            Description = "Ipsam tempora quas adipisci sit et et ex odit. Debitis modi natus in illo. Enim repellat quisquam quibusdam commodi ut. Modi et ipsa voluptates. Vero eum et aspernatur esse dolor voluptates alias fugit. Ullam consequatur repudiandae aut temporibus ab eaque.",
                            Name = "Facere quia veniam temporibus itaque recusandae eos."
                        },
                        new
                        {
                            ID = 4,
                            Description = "In natus dolor autem est sapiente molestias vero consectetur exercitationem. Et rerum quis velit neque ea voluptates et labore quia. Soluta ab sint voluptatum. Voluptatum blanditiis quaerat quidem mollitia debitis. Explicabo id in porro corrupti facilis. Et rerum porro deleniti et.",
                            Name = "Culpa voluptatem quia amet praesentium."
                        },
                        new
                        {
                            ID = 5,
                            Description = "Non et dolore omnis ad sed voluptas blanditiis ex. Hic reiciendis alias quia corporis quos cupiditate est. Itaque sapiente pariatur aut delectus. Est nostrum quis quis dolor sit vel. Omnis est et eveniet. Quia ad consequuntur voluptatem.",
                            Name = "Eius magnam iusto est."
                        },
                        new
                        {
                            ID = 6,
                            Description = "Quia voluptate deleniti sint quis ipsam. Unde doloribus qui quas. Cumque aut velit omnis in et sint dolorem similique. Nihil inventore et dicta. Quod qui et et adipisci id aut accusamus ea.",
                            Name = "Facere nulla beatae minus et accusamus tempora officia."
                        },
                        new
                        {
                            ID = 7,
                            Description = "Enim et assumenda qui iste totam qui est omnis. Autem tempora eum soluta repellat culpa tempore eum reiciendis itaque. Dolore nemo asperiores commodi.",
                            Name = "Magnam ut doloremque voluptate qui qui quas ratione aut."
                        },
                        new
                        {
                            ID = 8,
                            Description = "Incidunt sint aut dicta suscipit et. Ut pariatur fugit ut dicta fugiat rem est sint. Sunt fugiat vel vel eum quisquam excepturi adipisci qui. Veritatis pariatur enim et necessitatibus. Quod optio ipsa quia ratione dolor et molestiae incidunt suscipit. Dolorum dolore suscipit tempora id.",
                            Name = "Recusandae libero inventore veniam omnis ullam et magni at."
                        },
                        new
                        {
                            ID = 9,
                            Description = "In in velit est minus maiores beatae qui in. Vero quia quia quos veniam. Soluta et quis placeat amet.",
                            Name = "Omnis sit eligendi quia voluptas omnis."
                        },
                        new
                        {
                            ID = 10,
                            Description = "Quam qui qui et. Sunt error fugiat laboriosam similique. Eum et doloremque occaecati architecto et dolores reiciendis adipisci. Alias voluptate ipsum doloribus explicabo. Praesentium facere iste excepturi aut ut quaerat sit.",
                            Name = "Fugiat fugit in nisi deleniti eum est nobis vero."
                        },
                        new
                        {
                            ID = 11,
                            Description = "Est sunt nisi et facere est non. Velit dolores eum omnis voluptate sint laudantium minus illum. Numquam nisi dolores accusantium officiis. Ea iusto ut molestias laudantium. Tempora repudiandae voluptatibus ipsa quia similique.",
                            Name = "Et dolorem debitis ea nesciunt porro rem aspernatur."
                        },
                        new
                        {
                            ID = 12,
                            Description = "Quis consequuntur molestiae voluptate autem maxime assumenda. Quia fugiat cupiditate nisi. Atque voluptatem qui aut. Nihil amet sapiente doloremque aut qui. Quia et et alias.",
                            Name = "Et et qui et tenetur sequi nesciunt."
                        },
                        new
                        {
                            ID = 13,
                            Description = "Hic ut sed amet non ut quo. Saepe sint aut delectus amet ipsa repellat. Tempore aut error aut quia inventore. Eum occaecati et odio at nisi.",
                            Name = "Ipsa hic recusandae nostrum."
                        },
                        new
                        {
                            ID = 14,
                            Description = "Harum error ea explicabo quidem. Velit in totam labore. Iste enim amet eos distinctio non necessitatibus nesciunt dignissimos consectetur.",
                            Name = "Expedita expedita sit aut iste voluptatem animi vel non."
                        },
                        new
                        {
                            ID = 15,
                            Description = "Ipsum non dignissimos accusantium dolore quidem nobis et. Iusto sint quos quia nisi sit totam id voluptatum. Facilis ullam sed enim tenetur ut quia iure.",
                            Name = "Ullam exercitationem repudiandae non eum atque."
                        },
                        new
                        {
                            ID = 16,
                            Description = "Ipsam quas delectus in illo enim. Natus in ad fugit laborum. Rerum voluptatem vitae corrupti est beatae.",
                            Name = "Omnis ut cumque et suscipit culpa."
                        },
                        new
                        {
                            ID = 17,
                            Description = "Dolores a voluptatibus doloribus corrupti nostrum id. Ut nihil officiis temporibus sed non quas. Nulla qui aut et aut cum. Expedita aliquid et et asperiores numquam eius a vero. Id a quia omnis impedit. Delectus inventore laborum debitis dolorum aut.",
                            Name = "Rerum voluptatem sint qui architecto."
                        },
                        new
                        {
                            ID = 18,
                            Description = "Autem similique ipsa voluptate. Reprehenderit occaecati quia reiciendis maxime quisquam. Sed officiis magni id facilis maiores. Enim ut autem error. Vel dolor consectetur rem accusantium rerum atque quidem sed dolor. Nemo quis ipsam nesciunt voluptatibus cumque similique nulla provident expedita.",
                            Name = "Amet ut et excepturi adipisci quaerat."
                        },
                        new
                        {
                            ID = 19,
                            Description = "Quia consequatur aliquam id nobis. Officiis libero sed possimus dicta rerum fugit magnam aut. Veritatis laboriosam sunt quod ratione omnis exercitationem est ut.",
                            Name = "Itaque rerum eligendi delectus laboriosam et aut quae id."
                        },
                        new
                        {
                            ID = 20,
                            Description = "Tempore quaerat aperiam molestiae laboriosam nobis. Quasi distinctio rerum illo beatae beatae. Consectetur ipsa dolorem quia est. Atque ducimus reiciendis iste dolore non ea omnis. Distinctio minus ut harum repellat.",
                            Name = "Beatae aut quod sint accusantium ab beatae."
                        },
                        new
                        {
                            ID = 21,
                            Description = "Saepe consequuntur accusamus inventore sit fugiat sapiente. Repudiandae debitis fugit ipsam. Facilis eius voluptates aut qui voluptas animi. Id ut maiores ea accusamus eos consequatur. Eos est tempora nobis quasi delectus ab minus. Aut sapiente harum inventore veniam voluptatum.",
                            Name = "Et consequatur nisi eum eos nam magni tempore voluptatum consequatur."
                        },
                        new
                        {
                            ID = 22,
                            Description = "In saepe incidunt vitae in aliquam. Veniam pariatur harum magni vel. Illo tempore laboriosam dolor ut ut nisi.",
                            Name = "Iste aut ad sit nostrum eos eligendi animi dolore quisquam."
                        },
                        new
                        {
                            ID = 23,
                            Description = "Quisquam esse nemo numquam. Alias quia rerum et. Hic consequuntur cupiditate eligendi earum hic fugit placeat eligendi odit. Voluptas accusamus optio sint.",
                            Name = "Modi dolor nulla velit velit cupiditate voluptatem unde."
                        },
                        new
                        {
                            ID = 24,
                            Description = "Est qui omnis aut esse nulla. Quia nulla neque consequatur. Quidem perferendis nulla blanditiis sunt nulla assumenda.",
                            Name = "Nam repellendus molestias eveniet non aut."
                        },
                        new
                        {
                            ID = 25,
                            Description = "In aut sint deserunt beatae suscipit ut et voluptas. Impedit sed iure autem repellendus aut sunt eveniet fugiat non. Magni delectus quos sint cumque voluptatibus natus deserunt. Et vero qui non et quia labore. Aperiam et quae sint dolorum dolor.",
                            Name = "Delectus sint impedit voluptas harum perferendis at."
                        },
                        new
                        {
                            ID = 26,
                            Description = "Necessitatibus voluptatem sunt commodi repellendus. Cupiditate harum nisi expedita amet assumenda fugiat animi porro et. Quia iure omnis quam sint deleniti eaque facilis explicabo. Aut quo quidem consequatur sit rerum non est. Quos ipsum iste earum repellat quaerat et rem qui.",
                            Name = "Reiciendis eius voluptatem quia qui alias maiores."
                        },
                        new
                        {
                            ID = 27,
                            Description = "Reiciendis earum et quia laboriosam. Beatae at distinctio quibusdam ab sed. Qui excepturi eos quo autem aspernatur natus. Ea minus amet voluptatem provident et. Dolores corporis quidem et.",
                            Name = "Quidem officiis ipsa corrupti."
                        },
                        new
                        {
                            ID = 28,
                            Description = "Eligendi asperiores eius et voluptas libero voluptatem tenetur. Nulla cumque dolorem soluta facilis ut. Qui sint expedita animi qui. Aut hic ullam eius est et esse est aut quas.",
                            Name = "Fuga facere autem nam adipisci qui."
                        },
                        new
                        {
                            ID = 29,
                            Description = "Non sit nemo occaecati autem omnis. Repudiandae voluptas eos aut ullam sint maiores nostrum. Ea doloremque ipsum et repellat dolore repellat eveniet ut est.",
                            Name = "Adipisci quisquam deserunt cumque itaque optio nobis voluptatum ut."
                        });
                });

            modelBuilder.Entity("BackendTemplate.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Btw_Number")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Btw_Number = "88",
                            Email = "raymundo.wehner@mannlindgren.com",
                            FirstName = "Tamara",
                            LastName = "Bogisich",
                            Phone = "559-434-7951 x243"
                        },
                        new
                        {
                            ID = 2,
                            Btw_Number = "452",
                            Email = "pattie.oreilly@greenholthalvorson.info",
                            FirstName = "Hollie",
                            LastName = "Batz",
                            Phone = "(824)535-0773"
                        },
                        new
                        {
                            ID = 3,
                            Btw_Number = "593",
                            Email = "clint.williamson@kautzer.info",
                            FirstName = "Janae",
                            LastName = "Roberts",
                            Phone = "1-716-441-3206 x45516"
                        },
                        new
                        {
                            ID = 4,
                            Btw_Number = "77",
                            Email = "torrey@keelingkessler.biz",
                            FirstName = "Narciso",
                            LastName = "Walter",
                            Phone = "696.213.7918"
                        },
                        new
                        {
                            ID = 5,
                            Btw_Number = "184",
                            Email = "garry@jacobsmaggio.name",
                            FirstName = "Ova",
                            LastName = "Lang",
                            Phone = "(672)316-4757 x49586"
                        },
                        new
                        {
                            ID = 6,
                            Btw_Number = "337",
                            Email = "cierra.zboncak@volkmanbayer.com",
                            FirstName = "Ewald",
                            LastName = "Harber",
                            Phone = "1-004-948-0909 x709"
                        },
                        new
                        {
                            ID = 7,
                            Btw_Number = "618",
                            Email = "tevin@warddooley.uk",
                            FirstName = "Stefanie",
                            LastName = "Jast",
                            Phone = "(317)064-6597 x38929"
                        },
                        new
                        {
                            ID = 8,
                            Btw_Number = "467",
                            Email = "stanford@lockman.info",
                            FirstName = "Jevon",
                            LastName = "Paucek",
                            Phone = "1-489-621-3539 x89249"
                        },
                        new
                        {
                            ID = 9,
                            Btw_Number = "75",
                            Email = "leland@lakinbecker.us",
                            FirstName = "Nathanial",
                            LastName = "Turner",
                            Phone = "(993)676-2702 x752"
                        },
                        new
                        {
                            ID = 10,
                            Btw_Number = "877",
                            Email = "berry_champlin@barrowskunde.ca",
                            FirstName = "Randi",
                            LastName = "Sipes",
                            Phone = "1-376-105-4118"
                        },
                        new
                        {
                            ID = 11,
                            Btw_Number = "890",
                            Email = "bradley@goyette.uk",
                            FirstName = "Oswaldo",
                            LastName = "Herman",
                            Phone = "(121)385-6091"
                        },
                        new
                        {
                            ID = 12,
                            Btw_Number = "713",
                            Email = "crystal@wyman.uk",
                            FirstName = "Mikayla",
                            LastName = "Gorczany",
                            Phone = "1-154-635-0404"
                        },
                        new
                        {
                            ID = 13,
                            Btw_Number = "314",
                            Email = "london.dibbert@nicolas.ca",
                            FirstName = "Piper",
                            LastName = "Fadel",
                            Phone = "431.185.1610 x0542"
                        },
                        new
                        {
                            ID = 14,
                            Btw_Number = "121",
                            Email = "quincy.green@sauer.com",
                            FirstName = "Maudie",
                            LastName = "Murray",
                            Phone = "(727)183-1328"
                        },
                        new
                        {
                            ID = 15,
                            Btw_Number = "398",
                            Email = "ezequiel_lowe@hagenesebert.com",
                            FirstName = "Madge",
                            LastName = "Bradtke",
                            Phone = "043-543-2541"
                        },
                        new
                        {
                            ID = 16,
                            Btw_Number = "733",
                            Email = "doyle.goldner@mohr.com",
                            FirstName = "Onie",
                            LastName = "Wolf",
                            Phone = "(586)754-2819"
                        },
                        new
                        {
                            ID = 17,
                            Btw_Number = "573",
                            Email = "terrell@bauch.info",
                            FirstName = "Dejon",
                            LastName = "Jerde",
                            Phone = "1-134-068-8482"
                        },
                        new
                        {
                            ID = 18,
                            Btw_Number = "493",
                            Email = "denis_lockman@runolfsdottir.name",
                            FirstName = "Robbie",
                            LastName = "Monahan",
                            Phone = "219-371-1901 x4814"
                        },
                        new
                        {
                            ID = 19,
                            Btw_Number = "613",
                            Email = "freddy@jakubowskicorwin.name",
                            FirstName = "Iva",
                            LastName = "Vandervort",
                            Phone = "(034)939-7029"
                        },
                        new
                        {
                            ID = 20,
                            Btw_Number = "173",
                            Email = "herbert.runolfsdottir@emard.co.uk",
                            FirstName = "Tressie",
                            LastName = "O'Connell",
                            Phone = "(293)701-4907 x597"
                        },
                        new
                        {
                            ID = 21,
                            Btw_Number = "633",
                            Email = "kelsie.medhurst@daremoen.uk",
                            FirstName = "Merl",
                            LastName = "Block",
                            Phone = "961.411.1278 x2528"
                        },
                        new
                        {
                            ID = 22,
                            Btw_Number = "151",
                            Email = "jany.boehm@johnson.us",
                            FirstName = "Kaitlin",
                            LastName = "Bogisich",
                            Phone = "722.068.7119 x07510"
                        },
                        new
                        {
                            ID = 23,
                            Btw_Number = "166",
                            Email = "emmanuelle@corkery.com",
                            FirstName = "Felix",
                            LastName = "Steuber",
                            Phone = "048-325-7231"
                        },
                        new
                        {
                            ID = 24,
                            Btw_Number = "388",
                            Email = "wiley_boyer@lynchjones.com",
                            FirstName = "Ken",
                            LastName = "Lehner",
                            Phone = "460.315.3516"
                        },
                        new
                        {
                            ID = 25,
                            Btw_Number = "2",
                            Email = "emil@effertz.info",
                            FirstName = "Mathew",
                            LastName = "Lind",
                            Phone = "205-893-0423 x579"
                        },
                        new
                        {
                            ID = 26,
                            Btw_Number = "548",
                            Email = "danial_boyle@goldnerbode.ca",
                            FirstName = "Chasity",
                            LastName = "Hodkiewicz",
                            Phone = "1-259-849-8981"
                        },
                        new
                        {
                            ID = 27,
                            Btw_Number = "298",
                            Email = "modesto@kunze.com",
                            FirstName = "Neoma",
                            LastName = "Fadel",
                            Phone = "639.310.4181"
                        },
                        new
                        {
                            ID = 28,
                            Btw_Number = "255",
                            Email = "titus@kessler.com",
                            FirstName = "Carlee",
                            LastName = "Ernser",
                            Phone = "933.184.6133 x3133"
                        },
                        new
                        {
                            ID = 29,
                            Btw_Number = "393",
                            Email = "gustave.tillman@millerlebsack.ca",
                            FirstName = "Arno",
                            LastName = "Dickinson",
                            Phone = "1-650-007-8019 x800"
                        });
                });

            modelBuilder.Entity("BackendTemplate.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "florine@ullrich.us",
                            FirstName = "Lorenza",
                            LastName = "Funk",
                            Phone = "848-218-1256"
                        },
                        new
                        {
                            ID = 2,
                            Email = "antonetta_luettgen@sipes.biz",
                            FirstName = "Cristopher",
                            LastName = "Turner",
                            Phone = "1-303-161-2418 x82882"
                        },
                        new
                        {
                            ID = 3,
                            Email = "jaclyn_mcdermott@mullerwilliamson.name",
                            FirstName = "America",
                            LastName = "Brekke",
                            Phone = "(641)431-0782 x522"
                        },
                        new
                        {
                            ID = 4,
                            Email = "janet@larson.uk",
                            FirstName = "Millie",
                            LastName = "McGlynn",
                            Phone = "(878)613-9514"
                        },
                        new
                        {
                            ID = 5,
                            Email = "wilma@cummeratafeil.com",
                            FirstName = "Colby",
                            LastName = "Schinner",
                            Phone = "407-353-8535 x3757"
                        },
                        new
                        {
                            ID = 6,
                            Email = "jettie.farrell@gutmann.uk",
                            FirstName = "Mac",
                            LastName = "Balistreri",
                            Phone = "274-240-3523 x734"
                        },
                        new
                        {
                            ID = 7,
                            Email = "sabrina@lakin.com",
                            FirstName = "Tyreek",
                            LastName = "Mayert",
                            Phone = "687-103-8864"
                        },
                        new
                        {
                            ID = 8,
                            Email = "percival_yost@ebert.com",
                            FirstName = "Gia",
                            LastName = "Armstrong",
                            Phone = "176-919-3069 x0404"
                        },
                        new
                        {
                            ID = 9,
                            Email = "ruth_morissette@okon.info",
                            FirstName = "Brad",
                            LastName = "Kuphal",
                            Phone = "718.303.7573 x5312"
                        },
                        new
                        {
                            ID = 10,
                            Email = "raleigh_zemlak@lowe.info",
                            FirstName = "Mose",
                            LastName = "Okuneva",
                            Phone = "798-296-3573"
                        },
                        new
                        {
                            ID = 11,
                            Email = "easton_murray@grant.com",
                            FirstName = "Chaim",
                            LastName = "Brekke",
                            Phone = "633.119.7342"
                        },
                        new
                        {
                            ID = 12,
                            Email = "melvina.nolan@weimannhegmann.biz",
                            FirstName = "Ava",
                            LastName = "Dooley",
                            Phone = "271.941.2268 x2436"
                        },
                        new
                        {
                            ID = 13,
                            Email = "maybell_murphy@schuppecremin.info",
                            FirstName = "Lolita",
                            LastName = "Tillman",
                            Phone = "576-875-5973"
                        },
                        new
                        {
                            ID = 14,
                            Email = "rupert_prosacco@jacobs.name",
                            FirstName = "Clinton",
                            LastName = "Tromp",
                            Phone = "(559)029-3390"
                        },
                        new
                        {
                            ID = 15,
                            Email = "toni_rath@wymankub.ca",
                            FirstName = "Grover",
                            LastName = "Langosh",
                            Phone = "(070)767-4825"
                        },
                        new
                        {
                            ID = 16,
                            Email = "tanner@schultz.info",
                            FirstName = "Meggie",
                            LastName = "Hessel",
                            Phone = "951-382-8393"
                        },
                        new
                        {
                            ID = 17,
                            Email = "noe@reynolds.name",
                            FirstName = "Emerald",
                            LastName = "Weimann",
                            Phone = "1-582-204-0036"
                        },
                        new
                        {
                            ID = 18,
                            Email = "muhammad@hane.us",
                            FirstName = "Sigrid",
                            LastName = "Jewess",
                            Phone = "1-389-123-6787 x1060"
                        },
                        new
                        {
                            ID = 19,
                            Email = "rowan.koelpin@rowebernier.info",
                            FirstName = "Brandy",
                            LastName = "Feest",
                            Phone = "(768)336-3108 x315"
                        },
                        new
                        {
                            ID = 20,
                            Email = "bernadette@gaylordmoore.us",
                            FirstName = "Charlene",
                            LastName = "Carter",
                            Phone = "952-787-1959 x9556"
                        },
                        new
                        {
                            ID = 21,
                            Email = "raymond.muller@volkmantromp.info",
                            FirstName = "Marion",
                            LastName = "Pollich",
                            Phone = "371-736-4560 x1301"
                        },
                        new
                        {
                            ID = 22,
                            Email = "melody@jacobs.com",
                            FirstName = "Peyton",
                            LastName = "Williamson",
                            Phone = "(044)191-5146"
                        },
                        new
                        {
                            ID = 23,
                            Email = "stephen@zboncak.com",
                            FirstName = "Marquise",
                            LastName = "Wunsch",
                            Phone = "1-901-429-2630 x6707"
                        },
                        new
                        {
                            ID = 24,
                            Email = "mac_spinka@schulist.name",
                            FirstName = "Alfreda",
                            LastName = "Boehm",
                            Phone = "1-227-592-2964"
                        },
                        new
                        {
                            ID = 25,
                            Email = "herminio@swift.name",
                            FirstName = "Ezekiel",
                            LastName = "Osinski",
                            Phone = "(271)107-8706 x009"
                        },
                        new
                        {
                            ID = 26,
                            Email = "noemi@tremblay.com",
                            FirstName = "Reuben",
                            LastName = "Lueilwitz",
                            Phone = "988-757-3229"
                        },
                        new
                        {
                            ID = 27,
                            Email = "eleanora@olson.uk",
                            FirstName = "Elissa",
                            LastName = "Treutel",
                            Phone = "1-258-971-8290 x59061"
                        },
                        new
                        {
                            ID = 28,
                            Email = "evelyn@larkin.co.uk",
                            FirstName = "Ephraim",
                            LastName = "Walter",
                            Phone = "686.691.2877 x55154"
                        },
                        new
                        {
                            ID = 29,
                            Email = "isabella@koss.us",
                            FirstName = "Alene",
                            LastName = "Fritsch",
                            Phone = "497-417-2030"
                        });
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Estimated_Finish_Time")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Architecto debitis minus omnis et porro praesentium dolor recusandae quaerat. Et est at aut occaecati autem suscipit. Accusamus reiciendis ipsa eum a et. Necessitatibus ad vel impedit beatae in perferendis aspernatur corrupti autem. Ea sed voluptates quod. Sed explicabo dolore quisquam modi alias.",
                            Price = 230,
                            Title = "Consectetur consequuntur eveniet voluptate modi."
                        },
                        new
                        {
                            ID = 2,
                            Description = "Vitae facilis et ratione praesentium est minima iure. Quas amet reprehenderit laborum consectetur sequi dolor voluptas est dolorem. Sint voluptatibus reprehenderit ut. Eveniet laborum voluptate aspernatur occaecati ea dolores repellendus.",
                            Price = 955,
                            Title = "Ratione laborum possimus animi quis enim optio eveniet aut."
                        },
                        new
                        {
                            ID = 3,
                            Description = "Et numquam animi doloribus occaecati eum cupiditate est. Corporis quis molestias nemo. Debitis eum molestiae dolor impedit nobis. Cumque distinctio quidem nostrum exercitationem dolores beatae et.",
                            Price = 776,
                            Title = "Harum sequi labore veniam."
                        },
                        new
                        {
                            ID = 4,
                            Description = "Ut ad a rerum sint dolorem. Ducimus dolorem odit dolor earum labore saepe voluptatem. Assumenda et ut natus vitae. Iusto ab cum laboriosam et. Eum qui minus quibusdam inventore suscipit dolores.",
                            Price = 433,
                            Title = "Iure velit sit iure alias beatae voluptatem atque."
                        },
                        new
                        {
                            ID = 5,
                            Description = "Assumenda qui explicabo provident culpa veritatis minima libero consequatur inventore. Ratione necessitatibus earum quo occaecati amet sint illo aut ullam. Distinctio recusandae omnis adipisci eum et at. Quis ullam harum et molestiae dolores adipisci quam molestias. Et assumenda temporibus quibusdam veniam et voluptas autem iusto.",
                            Price = 525,
                            Title = "Earum soluta rem unde ut reprehenderit temporibus."
                        },
                        new
                        {
                            ID = 6,
                            Description = "Qui repellat et incidunt autem perspiciatis. Quidem blanditiis placeat perferendis atque ex. Ex enim ut qui aut qui aliquid vel. Occaecati dolorem tempora neque sapiente dolor quaerat voluptatibus sit.",
                            Price = 36,
                            Title = "Quo molestiae et eum sapiente eius asperiores voluptate voluptas deserunt."
                        },
                        new
                        {
                            ID = 7,
                            Description = "Autem et sit sapiente labore tempore. Perferendis dolorem at voluptates suscipit ipsam. Corrupti minima animi reprehenderit blanditiis. Omnis enim quisquam sit. Similique aspernatur vel similique. Consectetur nobis libero accusantium nulla eos iste nisi minima est.",
                            Price = 151,
                            Title = "Vel eos beatae vel officiis itaque omnis et adipisci dolor."
                        },
                        new
                        {
                            ID = 8,
                            Description = "Adipisci inventore tempora voluptatum quia incidunt sed blanditiis facere ut. Ut sint aut non. Consequatur dolor quia qui occaecati in dolor.",
                            Price = 415,
                            Title = "Et officiis exercitationem libero odio velit vel eos aut."
                        },
                        new
                        {
                            ID = 9,
                            Description = "Deleniti est sequi ut consequatur reprehenderit hic. Dolorum ut placeat incidunt ipsa aut eveniet repellendus cumque. Et veniam voluptatem itaque quae. Eveniet officia cupiditate unde. Quia qui ea nisi et. Velit eum a quidem sunt porro laboriosam est dolores sint.",
                            Price = 772,
                            Title = "Voluptatem perspiciatis quos incidunt delectus consequatur illo dolorum quibusdam cumque."
                        },
                        new
                        {
                            ID = 10,
                            Description = "Repellendus rem iste dolorem voluptatibus odio. Sint similique ducimus quo fugit rerum ut sed voluptas. Qui id debitis sint in. Voluptatibus consequatur exercitationem rerum nihil ut aut enim. Tempore soluta totam minus reprehenderit eum facere voluptatem quod omnis. Quis id quo possimus consectetur soluta omnis.",
                            Price = 910,
                            Title = "Officia iste in explicabo nemo consequuntur perferendis placeat."
                        },
                        new
                        {
                            ID = 11,
                            Description = "Dolore aperiam eos rerum eaque consequatur officiis ut. Laborum fugit quisquam et qui iure ullam velit. Laborum et est voluptas exercitationem debitis. Et esse ut et quasi exercitationem odit magni. Libero qui cumque molestiae vero vel nam ex consequatur amet.",
                            Price = 661,
                            Title = "Eius est quis est sequi reprehenderit non error."
                        },
                        new
                        {
                            ID = 12,
                            Description = "Rerum voluptas quas unde architecto voluptates officia nam qui. Repellendus molestiae natus explicabo repellendus. Cumque sunt repudiandae ipsum aut quis sequi adipisci unde aut.",
                            Price = 347,
                            Title = "Quidem et laborum deleniti aut culpa doloribus assumenda ut possimus."
                        },
                        new
                        {
                            ID = 13,
                            Description = "Et ut dolorum quis nesciunt. Id porro quae consequuntur. Non accusantium eius corporis voluptatem aliquam rerum est et.",
                            Price = 361,
                            Title = "Accusantium odit eos est praesentium."
                        },
                        new
                        {
                            ID = 14,
                            Description = "Atque ad accusamus a iure. Rerum commodi eos numquam quam et consectetur dolor dolor. Id dolores rem non voluptatem voluptatem. Voluptatibus beatae nemo earum vero asperiores consectetur et optio. Quidem voluptas harum ut totam qui. Nihil sint aut sunt et sit facilis minus praesentium.",
                            Price = 597,
                            Title = "Rerum odio recusandae consectetur quod voluptas aliquam."
                        },
                        new
                        {
                            ID = 15,
                            Description = "Ut nisi omnis eius. Cupiditate voluptate aspernatur alias expedita aspernatur nihil cum. Quis sed quia distinctio laborum qui facere. Aut dolores provident nobis unde odit suscipit.",
                            Price = 614,
                            Title = "Ut enim natus et architecto aut pariatur."
                        },
                        new
                        {
                            ID = 16,
                            Description = "Architecto sit ut debitis. Odio commodi porro sapiente ea occaecati repudiandae praesentium inventore. Optio consequatur dolores et maxime aut expedita. Sit quos unde consequatur et quis doloremque vitae. Vero distinctio id temporibus alias magni et consectetur quia aliquid. Et sapiente omnis rem autem eum est ut.",
                            Price = 918,
                            Title = "Repellat animi et rerum in."
                        },
                        new
                        {
                            ID = 17,
                            Description = "Eligendi qui corporis dolores odio magnam vero debitis. Sed qui adipisci distinctio in eos. Enim saepe corporis laboriosam et.",
                            Price = 231,
                            Title = "Provident facilis dignissimos facilis magnam."
                        },
                        new
                        {
                            ID = 18,
                            Description = "Dignissimos id dignissimos qui reprehenderit aliquid qui ut numquam error. Nihil doloremque et blanditiis est excepturi soluta repellendus temporibus dolore. Modi et dolor dolores. Placeat fugit alias laboriosam id corrupti ratione ut. Asperiores illo perspiciatis culpa cum voluptas.",
                            Price = 986,
                            Title = "Earum maiores aut quis libero suscipit id porro."
                        },
                        new
                        {
                            ID = 19,
                            Description = "Repellat architecto asperiores sed. Nihil aut saepe aut aliquid. Et cumque maxime ut consequatur. Ut perspiciatis vitae suscipit. Voluptas aut eius neque sit quam tenetur laudantium sunt.",
                            Price = 519,
                            Title = "Consectetur recusandae quam excepturi sequi voluptas at ipsum aspernatur et."
                        },
                        new
                        {
                            ID = 20,
                            Description = "Quos aliquam non blanditiis ad recusandae assumenda nihil. Est fugiat asperiores qui qui eum impedit. Est necessitatibus sunt beatae quo soluta asperiores fugit aut.",
                            Price = 454,
                            Title = "Rerum laboriosam numquam ut non voluptatem repellat."
                        },
                        new
                        {
                            ID = 21,
                            Description = "Iste qui facere repudiandae eum eos ipsam natus sed iste. Similique in et enim. Explicabo qui eum sit molestiae eum enim ratione occaecati cumque.",
                            Price = 19,
                            Title = "Expedita quisquam et reiciendis."
                        },
                        new
                        {
                            ID = 22,
                            Description = "Et quasi omnis odit aut aut. Quo sit non aut in debitis et sed. Amet cumque quidem id sequi pariatur fugit non explicabo. Beatae voluptates reprehenderit sit illum voluptas ullam qui.",
                            Price = 343,
                            Title = "Est doloribus impedit qui enim commodi voluptates similique autem veritatis."
                        },
                        new
                        {
                            ID = 23,
                            Description = "Occaecati aut voluptas debitis occaecati dolore qui numquam qui qui. Nulla recusandae consequatur quidem in. Aliquam et sed quam similique dolores delectus labore. Necessitatibus reiciendis sed sed doloribus debitis tempora.",
                            Price = 878,
                            Title = "Rerum itaque consequatur quibusdam porro labore consequatur animi."
                        },
                        new
                        {
                            ID = 24,
                            Description = "Similique repudiandae voluptatem tempora totam sed perspiciatis dolor eos in. Et aut dolorum odio corrupti ad perferendis quas eligendi ut. Vero id sed voluptatem assumenda voluptatem aut rerum laborum. Praesentium nihil asperiores voluptatem facere.",
                            Price = 260,
                            Title = "Aut aut voluptatibus a aut voluptate iste sit eos."
                        },
                        new
                        {
                            ID = 25,
                            Description = "Nemo et in accusantium debitis et assumenda voluptatem. Qui nisi sit voluptatibus non. A delectus eum odio porro aut modi ipsam quas.",
                            Price = 55,
                            Title = "Eum laborum expedita possimus distinctio."
                        },
                        new
                        {
                            ID = 26,
                            Description = "Aut deserunt qui harum molestiae minima fugit minima tempora vero. Inventore quia qui quia soluta fugiat. Molestiae distinctio ex voluptatem voluptas voluptatibus sint accusamus. Quo quidem pariatur vero.",
                            Price = 417,
                            Title = "Accusamus est omnis mollitia."
                        },
                        new
                        {
                            ID = 27,
                            Description = "Cupiditate sit tempore quae nesciunt modi est ab. Et id fugiat ut. Dolores atque maxime ut est. Ut est eaque sint quisquam qui.",
                            Price = 405,
                            Title = "Iusto qui quod debitis nobis consequatur natus."
                        },
                        new
                        {
                            ID = 28,
                            Description = "Adipisci ut deleniti quibusdam eum et saepe. Autem quae dolor dolor eum eaque. Doloremque beatae eos dolorem molestias suscipit. Necessitatibus corporis sit suscipit. Commodi architecto similique earum itaque. Quidem consequatur suscipit vero perspiciatis.",
                            Price = 250,
                            Title = "Rerum fugit voluptatem fuga quasi et velit ipsam."
                        },
                        new
                        {
                            ID = 29,
                            Description = "Blanditiis fuga aut maxime exercitationem reiciendis. Ut voluptas nihil assumenda ut aperiam. Fugiat corrupti corporis consequatur rerum ab. Sint velit asperiores nihil est rem aspernatur. Ullam distinctio eum sequi. Voluptatem voluptatem corporis voluptatem repellat maiores sunt.",
                            Price = 883,
                            Title = "Ex deserunt temporibus voluptas adipisci neque molestiae."
                        });
                });

            modelBuilder.Entity("BackendTemplate.Models.Subproject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Finish_Date")
                        .HasColumnType("text");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Start_Date")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Subprojects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Beatae unde autem doloribus praesentium consequuntur autem. Rerum aspernatur facilis earum ipsam quo. Debitis rerum ad quae nihil illum est.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Inventore necessitatibus quidem libero expedita quis cum."
                        },
                        new
                        {
                            ID = 2,
                            Description = "Sed saepe quasi enim sunt. Repellat delectus numquam velit perspiciatis. Praesentium omnis corrupti similique consequatur iure aut at vero. Sed earum aliquid consequatur saepe. Animi et voluptatum omnis ad aspernatur hic.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Quis minima distinctio exercitationem soluta temporibus voluptatem dolorum."
                        },
                        new
                        {
                            ID = 3,
                            Description = "Neque perferendis sint quo voluptatem quod ullam reiciendis quae vero. Dolor eos sed magnam beatae id quo iusto. Laudantium quia esse repellat.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Aut numquam consectetur itaque in quae."
                        },
                        new
                        {
                            ID = 4,
                            Description = "Minus veniam est sed dolores qui est sequi et repudiandae. Ut expedita sapiente distinctio aspernatur laudantium inventore quidem delectus. Perspiciatis asperiores quia quia.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Est exercitationem et occaecati eveniet."
                        },
                        new
                        {
                            ID = 5,
                            Description = "Et dolores et hic consequatur dolorum ea suscipit ut. Suscipit facilis et iste. Cum repellendus quae eum sunt. Alias dicta sunt aut nulla soluta quam soluta. Perferendis qui fugit eos explicabo.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Occaecati facere in velit nulla possimus voluptatem non ea."
                        },
                        new
                        {
                            ID = 6,
                            Description = "Eligendi voluptas a aut est aut quos. Saepe non omnis nihil officiis maxime ea. In quia molestiae sit mollitia reprehenderit. Doloremque autem autem eum. Quidem sed ut sit ad. Natus quae voluptas dolore ad et.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Quia distinctio quis minima nihil eveniet."
                        },
                        new
                        {
                            ID = 7,
                            Description = "Et ut ex voluptas molestiae consequuntur dolores dolorem reprehenderit. Dolor quam voluptas esse. Quaerat aliquid cum assumenda.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Repudiandae assumenda cumque ea at."
                        },
                        new
                        {
                            ID = 8,
                            Description = "Consectetur voluptatem quia veniam nobis nostrum. Omnis nostrum et quo porro. Dolor expedita veritatis corporis aut quia. Veniam eaque deserunt amet doloribus velit ullam quia. Sunt explicabo illum fuga delectus blanditiis minus cum porro est.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Quo expedita harum excepturi non velit iusto voluptas."
                        },
                        new
                        {
                            ID = 9,
                            Description = "Officiis nisi nihil omnis ab libero quaerat omnis qui. Blanditiis animi blanditiis ut exercitationem eligendi ducimus consequatur. Quos enim cum necessitatibus alias qui similique dolores similique ipsum. Sed sint eos modi eum. Odio voluptatum voluptatem molestiae assumenda praesentium odit consequatur et natus.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Cupiditate voluptate quae aperiam qui omnis molestiae eius libero."
                        },
                        new
                        {
                            ID = 10,
                            Description = "Ratione facilis esse esse consequatur consequatur non laudantium nesciunt. Laboriosam minus illum explicabo. Magni id facere nihil iusto quisquam.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Nam aut aut nobis reprehenderit repellendus ut."
                        },
                        new
                        {
                            ID = 11,
                            Description = "Doloribus sequi ad animi. Porro hic et sed. Sint molestiae accusamus ut qui optio vel amet et minus. Facere numquam omnis sint quis. Sed rerum quaerat ipsum molestias corrupti aut sunt maiores nihil.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Aspernatur minus corporis consequatur."
                        },
                        new
                        {
                            ID = 12,
                            Description = "Perspiciatis repudiandae qui similique consequatur et est et voluptatem. Et ut necessitatibus eum commodi ad nesciunt reprehenderit. Dicta dolores ut doloribus sint. Error sit quia aut hic voluptatum reiciendis. Molestias doloribus et repudiandae.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Perferendis beatae maxime ratione debitis quo ab voluptatem repellat."
                        },
                        new
                        {
                            ID = 13,
                            Description = "Dolorum cupiditate non aut tempora laboriosam. Et et omnis et qui. Et reprehenderit quod dignissimos aut.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Ut corrupti quos aperiam animi."
                        },
                        new
                        {
                            ID = 14,
                            Description = "Cupiditate sint sed consequatur est harum dicta sit. Distinctio quaerat repellendus et et magni fugiat. Aut quo error iure unde vel et ullam. Nam possimus esse soluta laborum et nulla fuga adipisci.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Velit iure rem deleniti beatae magnam."
                        },
                        new
                        {
                            ID = 15,
                            Description = "Vitae repellat voluptatum voluptatem sapiente ipsam aut saepe eum. Quia nobis quasi dolores aut. Molestias autem ratione nam excepturi optio adipisci. Ut ea quisquam unde fugit quis.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Nihil sint rem corrupti iusto accusamus sed repudiandae ut."
                        },
                        new
                        {
                            ID = 16,
                            Description = "Consequatur quisquam sint dignissimos optio velit blanditiis odio unde sed. Quam est hic fuga voluptate qui. Distinctio voluptate soluta sequi nostrum dolor recusandae.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Quia aperiam sunt nam nihil."
                        },
                        new
                        {
                            ID = 17,
                            Description = "Blanditiis aut sit inventore dolores consequatur laborum numquam atque. Labore eius voluptate est amet ut expedita aliquid earum quae. Minima facere quia quia voluptatum eos quis voluptatibus. Doloribus laborum modi consectetur. Atque voluptatum ratione eius culpa.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Fuga dolor nostrum aliquam."
                        },
                        new
                        {
                            ID = 18,
                            Description = "Nihil maxime nihil quia. Veniam consequatur sit dolores perspiciatis quia quis. Hic optio nisi omnis ducimus autem et ut reiciendis. Aperiam molestiae numquam architecto. Quis impedit velit temporibus.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Laudantium explicabo doloribus modi nulla aliquid consequuntur quaerat veritatis optio."
                        },
                        new
                        {
                            ID = 19,
                            Description = "Repudiandae odio quae eaque inventore voluptate quasi. Omnis repellendus soluta tempore sit dolores amet. Consectetur non quidem quasi non deserunt corrupti. Aperiam error aut explicabo vel.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Et est qui ea eveniet iusto mollitia enim."
                        },
                        new
                        {
                            ID = 20,
                            Description = "Velit dolorum id qui suscipit quibusdam cupiditate doloremque consectetur. Debitis accusamus voluptas laboriosam. Sint aliquid nam voluptatem.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Voluptatem eius occaecati officia."
                        },
                        new
                        {
                            ID = 21,
                            Description = "Quam nulla quos animi qui. Facilis non earum non error. Sunt eos consectetur officia voluptatem qui. Et harum ea ratione aut officiis.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Occaecati vel beatae vel minima autem laborum."
                        },
                        new
                        {
                            ID = 22,
                            Description = "Aliquid possimus voluptas suscipit unde aut. Id neque fugiat explicabo non nihil suscipit quibusdam. Dolores labore rerum fuga eligendi quia omnis. Vel voluptatibus illum et rem. Voluptatem voluptatum possimus doloremque impedit. Aspernatur at incidunt aliquam molestias.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Ut ab quas et atque quam labore."
                        },
                        new
                        {
                            ID = 23,
                            Description = "Non ab impedit consequatur porro itaque sit dolore. Sint voluptatem consectetur dignissimos autem nisi alias sequi quo rerum. Aut itaque quo tempora veniam.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Cumque et dolores et voluptatem enim dolores et at nemo."
                        },
                        new
                        {
                            ID = 24,
                            Description = "Deserunt voluptate distinctio sit consequatur iusto ipsam. Nobis vero earum aliquid optio. Et saepe nisi quia eos enim voluptas aspernatur aliquam libero. Aperiam molestias doloribus officia sed autem necessitatibus dolore molestias provident. Temporibus in nisi non consequatur esse.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Natus exercitationem labore qui expedita magni."
                        },
                        new
                        {
                            ID = 25,
                            Description = "Eos tempora ex voluptate voluptatem. Esse nesciunt tenetur a ut vel vel occaecati tempora. Quos aut cum voluptates velit consequatur sit dolorem a. Odit est non ratione dolorem. Necessitatibus et aliquid numquam.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Deleniti ea itaque autem et accusantium consectetur aut porro temporibus."
                        },
                        new
                        {
                            ID = 26,
                            Description = "Dolorem suscipit asperiores voluptas eos maiores quaerat. Accusamus dolores amet reiciendis voluptas. Veritatis id autem voluptatem. Nihil earum corrupti beatae corporis sit dolor sit nemo cum. Inventore nemo incidunt sit exercitationem. Ut non earum error soluta rerum ducimus illum.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 0,
                            Title = "Quos nihil voluptas omnis et sint animi ut magnam."
                        },
                        new
                        {
                            ID = 27,
                            Description = "Labore facere corporis esse aut blanditiis quibusdam. Vero velit possimus earum. Alias facere beatae consequuntur. Iure iste voluptatum voluptatibus. Voluptatem qui ducimus aliquid. Illo minus possimus quam autem.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Et beatae ab quia."
                        },
                        new
                        {
                            ID = 28,
                            Description = "Vel at dolorem quo et optio id fuga. Accusamus quia eligendi accusantium voluptas aliquid. Optio aut id dolores et praesentium est aut dolores. Accusantium aspernatur incidunt tempora tempore et rerum.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 2,
                            Title = "Aut sint molestiae necessitatibus tenetur culpa dolores id."
                        },
                        new
                        {
                            ID = 29,
                            Description = "Rerum distinctio doloribus iusto. Tempora ad reprehenderit itaque voluptates neque voluptatem. Architecto nostrum quis expedita in aliquid qui. Et eius aliquid quia. Blanditiis voluptas maxime in accusamus officia.",
                            Finish_Date = "23/08/2001",
                            Start_Date = "23/07/2001",
                            State = 1,
                            Title = "Quae illo assumenda est blanditiis vitae dolorem facere at eius."
                        });
                });

            modelBuilder.Entity("ClientEmployee", b =>
                {
                    b.Property<int>("ClientsID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesID")
                        .HasColumnType("int");

                    b.HasKey("ClientsID", "EmployeesID");

                    b.HasIndex("EmployeesID");

                    b.ToTable("ClientEmployee");
                });

            modelBuilder.Entity("EmployeeSubproject", b =>
                {
                    b.Property<int>("EmployeesID")
                        .HasColumnType("int");

                    b.Property<int>("SubprojectsID")
                        .HasColumnType("int");

                    b.HasKey("EmployeesID", "SubprojectsID");

                    b.HasIndex("SubprojectsID");

                    b.ToTable("EmployeeSubproject");
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.HasOne("BackendTemplate.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientID");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BackendTemplate.Models.Subproject", b =>
                {
                    b.HasOne("BackendTemplate.Models.Category", "Category")
                        .WithMany("Subprojects")
                        .HasForeignKey("CategoryID");

                    b.HasOne("BackendTemplate.Models.Project", "Project")
                        .WithMany("Subprojects")
                        .HasForeignKey("ProjectID");

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ClientEmployee", b =>
                {
                    b.HasOne("BackendTemplate.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTemplate.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeSubproject", b =>
                {
                    b.HasOne("BackendTemplate.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTemplate.Models.Subproject", null)
                        .WithMany()
                        .HasForeignKey("SubprojectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendTemplate.Models.Category", b =>
                {
                    b.Navigation("Subprojects");
                });

            modelBuilder.Entity("BackendTemplate.Models.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("BackendTemplate.Models.Project", b =>
                {
                    b.Navigation("Subprojects");
                });
#pragma warning restore 612, 618
        }
    }
}
