version: '3.4'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - general_network
    volumes:
      - ./database:/var/lib/mysql

  web:
    container_name: web
    image: ${DOCKER_REGISTRY-}backendtemplate
    build:
      context: .
      dockerfile: BackendTemplate/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRINGS: server=db;port=3306;database=${DB_DATABASE};user=root;password=${DB_ROOT_PASSWORD};
    ports:
      - "80:80"
    volumes:
      - ./BackendTemplate:/root/.aspnet/https:ro
    depends_on:
       - db
    networks:
      - general_network


networks:
  general_network:
    name: general_network
